/**
 * WsVaultBankcardSoap_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.aoindustries.creditcards.sagePayments.wsVaultBankcard;

public interface WsVaultBankcardSoap_PortType extends java.rmi.Remote {
    public com.aoindustries.creditcards.sagePayments.wsVaultBankcard.VAULT_BANKCARD_SALEResponseVAULT_BANKCARD_SALEResult VAULT_BANKCARD_SALE(java.lang.String m_ID, java.lang.String m_KEY, java.lang.String c_NAME, java.lang.String c_ADDRESS, java.lang.String c_CITY, java.lang.String c_STATE, java.lang.String c_ZIP, java.lang.String c_COUNTRY, java.lang.String c_EMAIL, java.lang.String GUID, java.lang.String t_CUSTOMER_NUMBER, java.lang.String t_AMT, java.lang.String t_SHIPPING, java.lang.String t_TAX, java.lang.String t_ORDERNUM, java.lang.String c_TELEPHONE, java.lang.String c_FAX, java.lang.String c_SHIP_NAME, java.lang.String c_SHIP_ADDRESS, java.lang.String c_SHIP_CITY, java.lang.String c_SHIP_STATE, java.lang.String c_SHIP_ZIP, java.lang.String c_SHIP_COUNTRY) throws java.rmi.RemoteException;
    public com.aoindustries.creditcards.sagePayments.wsVaultBankcard.VAULT_BANKCARD_AUTHONLYResponseVAULT_BANKCARD_AUTHONLYResult VAULT_BANKCARD_AUTHONLY(java.lang.String m_ID, java.lang.String m_KEY, java.lang.String c_NAME, java.lang.String c_ADDRESS, java.lang.String c_CITY, java.lang.String c_STATE, java.lang.String c_ZIP, java.lang.String c_COUNTRY, java.lang.String c_EMAIL, java.lang.String GUID, java.lang.String t_CUSTOMER_NUMBER, java.lang.String t_AMT, java.lang.String t_SHIPPING, java.lang.String t_TAX, java.lang.String t_ORDERNUM, java.lang.String c_TELEPHONE, java.lang.String c_FAX, java.lang.String c_SHIP_NAME, java.lang.String c_SHIP_ADDRESS, java.lang.String c_SHIP_CITY, java.lang.String c_SHIP_STATE, java.lang.String c_SHIP_ZIP, java.lang.String c_SHIP_COUNTRY) throws java.rmi.RemoteException;
    public com.aoindustries.creditcards.sagePayments.wsVaultBankcard.VAULT_BANKCARD_FORCEResponseVAULT_BANKCARD_FORCEResult VAULT_BANKCARD_FORCE(java.lang.String m_ID, java.lang.String m_KEY, java.lang.String c_NAME, java.lang.String c_ADDRESS, java.lang.String c_CITY, java.lang.String c_STATE, java.lang.String c_ZIP, java.lang.String c_COUNTRY, java.lang.String c_EMAIL, java.lang.String GUID, java.lang.String t_CUSTOMER_NUMBER, java.lang.String t_AMT, java.lang.String t_SHIPPING, java.lang.String t_TAX, java.lang.String t_ORDERNUM, java.lang.String c_TELEPHONE, java.lang.String c_FAX, java.lang.String c_SHIP_NAME, java.lang.String c_SHIP_ADDRESS, java.lang.String c_SHIP_CITY, java.lang.String c_SHIP_STATE, java.lang.String c_SHIP_ZIP, java.lang.String c_SHIP_COUNTRY) throws java.rmi.RemoteException;
    public com.aoindustries.creditcards.sagePayments.wsVaultBankcard.VAULT_BANKCARD_CREDITResponseVAULT_BANKCARD_CREDITResult VAULT_BANKCARD_CREDIT(java.lang.String m_ID, java.lang.String m_KEY, java.lang.String c_NAME, java.lang.String c_ADDRESS, java.lang.String c_CITY, java.lang.String c_STATE, java.lang.String c_ZIP, java.lang.String c_COUNTRY, java.lang.String c_EMAIL, java.lang.String GUID, java.lang.String t_CUSTOMER_NUMBER, java.lang.String t_AMT, java.lang.String t_SHIPPING, java.lang.String t_TAX, java.lang.String t_ORDERNUM, java.lang.String c_TELEPHONE, java.lang.String c_FAX, java.lang.String c_SHIP_NAME, java.lang.String c_SHIP_ADDRESS, java.lang.String c_SHIP_CITY, java.lang.String c_SHIP_STATE, java.lang.String c_SHIP_ZIP, java.lang.String c_SHIP_COUNTRY) throws java.rmi.RemoteException;
}
